title: Xiang Xiang's Homepage
page-top-title: Xiang Xiang
top-section-bg-text: Open-World Sensing
home-subtitle: Xiang Xiang&ensp;|&ensp;项翔
copyright-text: '&copy; Xiang Xiang 2023-2024. All Rights Reserved.'
