title: Xiang Xiang's Homepage
page-top-title: Sen Li
top-section-bg-text: Computer Vision
home-subtitle: Xiang Xiang&ensp;|&ensp;项翔
copyright-text: '&copy; Xiang Xiang 2023-2024. All Rights Reserved.'
