title: Xiang Xiang's Personal Homepage
page-top-title: Xiang Xiang
top-section-bg-text: Open-World Sensing
home-subtitle: Xiang Xiang&ensp;|&ensp;项翔
copyright-text: '&copy; Xiang Xiang 2020-2025. All Rights Reserved.'
